from enum import Enum


class RequestStatus(str, Enum):
    CLASSIFIED = "CLASSIFIED"
    NEED_CLARIFICATION = "NEED_CLARIFICATION"
    PRIORITIZED = "PRIORITIZED"
    APPROVAL_PENDING = "APPROVAL_PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    ESCALATED = "ESCALATED"
    IN_PROGRESS = "IN_PROGRESS"
    DONE = "DONE"